### ISSUE TITLE
NPM version behaves weirdly

### ISSUE THREAD

**Issue by hirasso** [abouolia/sticky-sidebar#11]
Hi there, thanks for your great work! Could it be that the NPM version of the script needs updating? It behaves weirdly, elements are 'flickering'...

**Comment by abouolia** [comment]
In these days i work on version 2 of the plugin (there's more improvements in performance and it will be 0 dependency) https://github.com/abouolia/sticky-sidebar/tree/develop, probably that caused conflict with branches, so i recommend you to download it from Github from master branch. Regards

**Comment by abouolia** [comment]
Now it works perfectly. Thanks
