### ISSUE TITLE
Example with the stickySidebar at the right column

### ISSUE THREAD

**Issue by degibons** [abouolia/sticky-sidebar#15]
Please, can you make the example with stickySidebar at the right column and content at the left. Like at this page - https://abouolia.github.io/sticky-sidebar/examples/basic.html, but vice-versa. Thanks in advance.

**Comment by degibons** [comment]
Sorry, I've made this issue a little rashly.

**Comment by aurora** [comment]
@degibons really? what did you find out about this - does it work for you on the right? i do not get it to work and looking at the source it seems it's only for left-side bars?
