### ISSUE TITLE
Migration to Vanilla JS seems to have broke everything.

### ISSUE THREAD

**Issue by joshbader** [abouolia/sticky-sidebar#18]
The jQuery plugin stopped working for me after this. Console errors state that stickySidebar is not a function.

**Comment by abouolia** [comment]
What console errors, it seems you're using ``src/sticky-sidebar.js`` not ``dist/sticky-sidebar.js`` please screenshot your console than give it to me.

**Comment by joshbader** [comment]
I am trying to use dist/jquery.sticky-sidebar.min.js

![screen shot 2017-09-06 at 1 39 31 pm](https://user-images.githubusercontent.com/3035031/30126121-f75b79cc-9308-11e7-8201-a4875fe56410.png)

**Comment by abouolia** [comment]
There's something wrong in declaration of the plugin. can you give an screenshot? here's how to use the plugin with jQuery https://abouolia.github.io/sticky-sidebar/#usage-with-jqueryzepto

**Comment by joshbader** [comment]
<img width="359" alt="screen shot 2017-09-06 at 1 48 08 pm" src="https://user-images.githubusercontent.com/3035031/30126506-1a47390c-930a-11e7-8cb9-7b1891b40c12.png">

**Comment by abouolia** [comment]
I've fixed it, check it out and give me your output.

**Comment by joshbader** [comment]
Getting this error now.

![screen shot 2017-09-06 at 2 35 16 pm](https://user-images.githubusercontent.com/3035031/30128433-a92a3240-9310-11e7-9163-c295a42e5e72.png)

**Comment by abouolia** [comment]
That error not related in that opened issue, anyway this error says one of ``.sticky`` elements not inside ``.page-body``.

**Comment by joshbader** [comment]
I'm pretty sure it is. Here is my markup...

<img width="359" alt="screen shot 2017-09-06 at 3 08 38 pm" src="https://user-images.githubusercontent.com/3035031/30129859-53102cde-9315-11e7-8390-0a49facb4144.png">

The plugin worked fine before the migration with the same markup.

**Comment by abouolia** [comment]
Hey bro, there's something wrong in your code, you defined ``containerSelector`` as ``.page-body`` and in your markup defined it as id. The plugin was right. the sticky sidebar not inside the container. Regards :)

**Comment by joshbader** [comment]
Haha, my bad, good catch. Thanks.
