### ISSUE TITLE
Can't "require" with browserify.

### ISSUE THREAD

**Issue by glutaminefree** [abouolia/sticky-sidebar#19]
Hi!
Good lib, thanks!
But after ```npm install --save sticky-sidebar``` and putting ```require('sticky-sidebar');``` in my code, gulp (on building project) says: ```cannot find module 'sticky-sidebar'```.
I think, you need to put _main_ directive to your _package.json_ file.

**Comment by traykovn** [comment]
Yes, with webpack too. Thanks for the great plugin!
