### ISSUE TITLE
Resize Sensor on Firefox and IE 11

### ISSUE THREAD

**Issue by timleblanc** [abouolia/sticky-sidebar#21]
Hi. Great plugin. I'm using sticky-sidebar.min.js. 

Everything seems to be working fine in Chrome, except I'm experiencing a little scroll flicker as the .inner-wrapper-sticky div changes from fixed to relative when reaching the end of the container element.

On the latest version of Firefox (55.0.3), the resize sensor does not seem to be working properly. I went ahead and tested this on the basic example of the plugin - https://abouolia.github.io/sticky-sidebar/examples/basic.html. Upon adding content to the sidebar and scrolling to bottom of the page, the sidebar crosses over into the footer.

Also, in IE 11 (11.1593.14393.0), the console is showing a 'SCRIPT445: Object doesn't support this action' error, in regards to CustomEvent initialization.

Please advise. Thanks!

**Comment by dangranata** [comment]
Jus wanted to chime in that I got the same error (`'SCRIPT445: Object doesn't support this action'` in the `eventTrigger()` function) on IE10.

**Comment by abouolia** [comment]
I know have delayed to reply on some issues because i was work on paid project so excuse me, after some time of debugging i decided to change the whole idea of resize sensor because does not work well on internet explorer versions so the day after tomorrow will be some big commits that will fix this issue. Regards.

**Comment by abouolia** [comment]
This issue is fixed and other you can what have been done from here https://github.com/abouolia/sticky-sidebar/releases/tag/3.2.0. Regards.
