### ISSUE TITLE
Fails on IE11?

### ISSUE THREAD

**Issue by dangranata** [abouolia/sticky-sidebar#23]
Apologies for not having more to go on at this stage, but something appears to be off on IE11. When I load `examples/basic.html`, I get no errors but the content disappears. (The error referenced in https://github.com/abouolia/sticky-sidebar/issues/21 fires when scrolling down the page, however.)

I'm not immediately able to see what's going on in the dev tools, but I suspect it might be related to the `object`. I'll investigate more tomorrow and add additional detail if I can find any.

**Comment by Slind14** [comment]
Same issue here. I would recommend to put the script into this block: 
```
<!--[if !IE]>
<![endif]-->
```

**Comment by rosivanov** [comment]
@Slind14 Hm, do you propose to omit IE ?

**Comment by Slind14** [comment]
yes, excluding it.

**Comment by rosivanov** [comment]
it's ok if you can ignor it

**Comment by abouolia** [comment]
Hey guys, in version 3.2.0 this issue is fixed and other, you can see what have been done. https://github.com/abouolia/sticky-sidebar/releases/tag/3.2.0 Regards.

**Comment by rosivanov** [comment]
Brilliant! Works fine in IE11. Thanks a lot! :smiley: 
@abouolia
