### ISSUE TITLE
innerWrapperSelector doesn't work?

### ISSUE THREAD

**Issue by dFelinger** [abouolia/sticky-sidebar#25]
https://abouolia.github.io/sticky-sidebar/examples/basic.html still creating inner-wrapper-sticky element
I found solution in 149 line - if( null !== this.sidebarInner ) should be: if( null === this.sidebarInner )

**Comment by abouolia** [comment]
Good catch @dFelinger 👍 , https://github.com/abouolia/sticky-sidebar/commit/c350ef87046e9a536a6d667fb7f937a08fe5551e
