### ISSUE TITLE
Sidebar moving too far

### ISSUE THREAD

**Issue by Slind14** [abouolia/sticky-sidebar#26]
Hi there,
I have a sidebar with a padding, which I (unfortunately) can't remove. This padding is causing the sidebar to move too far. See codepen:
https://codepen.io/Slind/full/EwVbPL

I would be grateful for any tips on how to resolve this.

**Comment by abouolia** [comment]
I've helped you but i have no time to give you details about the solution so you will figure it out by yourself. Regards. https://codepen.io/abouolia/pen/NaNRaa

**Comment by Slind14** [comment]
Thanks.
Unfortunately, I'm not able to use this solution, because the padding is dynamic based on theme and window size. I would like to avoid overwriting too much. Hence I resolved it this way:
https://github.com/Slind14/sticky-sidebar/blob/master/src/sticky-sidebar.js#L227

**Comment by nielsnuebel** [comment]
I've the same issue. Like your example https://codepen.io/abouolia/pen/NaNRaa

**Comment by Slind14** [comment]
@abouolia maybe this can be reopened, since the solution you provided is moving outside of the container
