### ISSUE TITLE
Sticky (sidebar) element smaller than child elements

### ISSUE THREAD

**Issue by Slind14** [abouolia/sticky-sidebar#27]
Once the sidebar docks at the bottom it is losing size, shrinking to a smaller size than its child elements.
This causes issues in cases where an `onverflow: hidden` is in use/required.

Is there any solution for this?

https://codepen.io/Slind/full/BwomrQ

**Comment by abouolia** [comment]
Hi @Slind14, Unfortunately you can't add `overflow: hidden` to sidebar if you want it to be sticky.

**Comment by Slind14** [comment]
Yes, that is what I like to see resolved. Unfortunately I can't work around it in my use case.
