### ISSUE TITLE
Wrong container inspection

### ISSUE THREAD

**Issue by t-kanstantsin** [abouolia/sticky-sidebar#29]
If container IS defined - it will be override with default (parent element).
https://github.com/abouolia/sticky-sidebar/blob/master/src/sticky-sidebar.js#L165

```javascript
// If there's no specific container, user parent of sidebar as container.
if( null !== this.container )
    this.container = this.sidebar.parentElement;
```
Should be: ```null === this.container ```

**Comment by abouolia** [comment]
Good catch @t-kanstantsin  👍, https://github.com/abouolia/sticky-sidebar/commit/c350ef87046e9a536a6d667fb7f937a08fe5551e

**Comment by t-kanstantsin** [comment]
Hi! You fix another same bug, not this.
You fixed bug for sidebarInner: https://github.com/abouolia/sticky-sidebar/blob/master/src/sticky-sidebar.js#L149
But there is the same for container: https://github.com/abouolia/sticky-sidebar/blob/master/src/sticky-sidebar.js#L165

**Comment by abouolia** [comment]
https://github.com/abouolia/sticky-sidebar/commit/3eb5eaa6b0f8f86a9d3305867e06f82d5e8b1d04
