### ISSUE TITLE
Bug with style update (traslateY) when CONTAINER-BOTTOM and size of sidebar is changed

### ISSUE THREAD

**Issue by degibons** [abouolia/sticky-sidebar#3]
I've noticed a bug when sidebar is in the bottom position (image 1) and it size is changed (image 2). Sensor detect changes, and update demensions (sidebarHeight and translateY) but styles not changes. Can you fix it?

![1](https://cloud.githubusercontent.com/assets/1196570/26577425/08b44996-4535-11e7-81a0-a3694e04ab75.jpg)
![2](https://cloud.githubusercontent.com/assets/1196570/26577429/0aede316-4535-11e7-8555-79a15c02acd2.jpg)

**Comment by abouolia** [comment]
I'm so sorry for delay, give me 12 hours and i'll fix it.

**Comment by abouolia** [comment]
It fixed https://github.com/abouolia/sticky-sidebar/commit/68a9be2e9ca30a5caf30ad5e72b2b2e0867bfaab
