### ISSUE TITLE
destroy() doesn't work

### ISSUE THREAD

**Issue by tizianodriol** [abouolia/sticky-sidebar#30]
If I use

var stickySidebar = new StickySidebar('#sidebar-container');
stickySidebar.destroy();

I get this error on browser console

Uncaught TypeError: this.removeEventListener is not a function
    at StickySidebar.destroy (sticky-sidebar.js:722)
    at theme.js:1288
    at dispatch (jquery-1.11.1.min.js:3)
    at r.handle (jquery-1.11.1.min.js:3)

Could you please check? Thanks!

**Comment by abouolia** [comment]
I fixed that in version 3.2.0, check it out. Thanks 👍
