### ISSUE TITLE
Still not usable with npm

### ISSUE THREAD

**Issue by Jan-LucaKlees** [abouolia/sticky-sidebar#31]
Some weeks ago I opened a PR that added the `main` attribute to the `package.json` pointing to `src/sticky-sidebar.js`. This way the package is usable with npm or similar package managers.

I now see that the value as changed to `**dist**/stikcy-sidebar.js` which renders it unusable with npm again.

The problem is, that only in the `src/sticky-sidebar.js` there is an `export` statement, exporting the StickySidbar class. This is crucial when you want to use it this package with `require` or `import`.

Please either set the attribute "main" in the `package.json` to `src/sticky-sidebar.js` again, or add an export statement to the `dist/sticky-sidebar.js` file.

**Comment by abouolia** [comment]
Now `dist/sticky-sidebar.js` is universal module definition and tested with rollup and browserify and it works great. check it out. Regards.
