### ISSUE TITLE
NPM package 3.2.0 contains older version

### ISSUE THREAD

**Issue by altearius** [abouolia/sticky-sidebar#33]
I'm looking at version 3.2.0 of the NPM package for `sticky-sidebar` (currently at https://registry.npmjs.org/sticky-sidebar/-/sticky-sidebar-3.2.0.tgz) and I notice that the actual JavaScript files included are not version 3.2.0:

\src\sticky-sidebar.js is version 2.3.0
\dist\sticky-sidebar.js is version 2.3.0
\dist\jquery.sticky-sidebar.js is version 2.3.0

\dist\jquery.sticky-sidebar.min.js is version 2.2.0
\dist\sticky-sidebar.min.js is version 2.2.0

Is this intentional?

**Comment by abouolia** [comment]
That was my mistake, fixed.
