### ISSUE TITLE
Negative top margin on sticky element

### ISSUE THREAD

**Issue by kiwimind** [abouolia/sticky-sidebar#36]
Hi,

Thanks for a great plugin, it's mostly working very well.

I'm hoping that there's going to be a straightforward way around what I'm trying to accomplish, but so far I've been unable to find one...

When I've got a sidebar with a negative top (or margin-top) value, to overlap a header element, I'm unable to get this to work as expected.

I can amend the code to add in the value of this negative top, amending the colliderTop and colliderBottom values to match, but I'm getting some weird overlapping issue with the footer not pushing the element up.

Is there something else I can check to get this working? I've been unable to find anything regarding offsetting margins or positioning amendments.

Thanks

**Comment by abouolia** [comment]
Almost understood, just one question, is there margin/padding top on body or html tag?

**Comment by kiwimind** [comment]
Thanks for the reply and sorry for the delay in getting back to you.

I've set up a simple codepen here: https://codepen.io/anon/pen/yzWOLO

This doesn't quite work either, as the background continues, but you can see what I mean about the negative top margin impacting when the text hits its top.

I've partly managed to negate this by adding magic numbers to the stickySidebar.js file by amending the colliderTop and colliderBottom values by the size of my negative margin. Not ideal, but seems to help.

It doesn't help, however, when the sidebar is taller than the screen.

I hope this makes sense.

Thanks

**Comment by abouolia** [comment]
Hi @kiwimind, amending sticky-sidebar.js is a bad idea, this my solution for your issue https://codepen.io/abouolia/pen/Vrwzxw :)

**Comment by kiwimind** [comment]
Hi @abouolia 

Thank you, that's a step in the right direction, however if you make the footer tall enough so that it affects the sticky sidebar, it ends up overlapping. Do you have any thoughts about that?

I've amended my actual site with your suggestions, and they've helped, however I'm getting the sidebar being pushed up prematurely.

**Comment by kiwimind** [comment]
This isn't solved, as there are still outstanding issues when there are negative values involved.

Can you please check my last post and see if there's anything that can be done?

Thanks.

**Comment by iamtekeste** [comment]
@abouolia In this issue you asked @kiwimind if there is a `padding` or `margin` on the `body` or `html` mine has `padding-top: 58px` on the `body` and the footer is not pushing the sticky sidebar at the right moment(the sticky sidebar is overlapping with the footer). How do you account for this kind of cases.

<img width="679" alt="screen shot 2017-12-05 at 3 52 15 pm" src="https://user-images.githubusercontent.com/1515815/33630256-ad0e0d9a-d9d4-11e7-9c04-7f1ef47110cc.png">


Thank you in advance!
