### ISSUE TITLE
ie 11 issue

### ISSUE THREAD

**Issue by MilanRabrenovic** [abouolia/sticky-sidebar#37]
is there any fix for ie11? Sidebar isn't working at all. I'm getting white field over my content

**Comment by abouolia** [comment]
Hi @MilanRabrenovic, it seems you used the old version, make sure to use latest version, regards :)

**Comment by MilanRabrenovic** [comment]
Yeah, I've figured it out. Thanks for the reply. Cheers

**Comment by abouolia** [comment]
You're welcome :)
