### ISSUE TITLE
Trying to reproduce it

### ISSUE THREAD

**Issue by rhazor** [abouolia/sticky-sidebar#39]
I don't get it working

http://jsfiddle.net/zzp63pyr/

**Comment by masiorama** [comment]
You are missing all css directives. FIrst you have to create  the layout with the sidebar, and THEN you can try to apply the plugin. For instance, try with bootstrap (https://getbootstrap.com/docs/3.3/css/).

**Comment by rhazor** [comment]
What CSS directives? What it has to do with Bootstrap? Doesn't matter anymore, solved with plain CSS, no JS needed.

**Comment by masiorama** [comment]
Your jsfiddle was completely missing css styles, so you weren't able to reproduce the functionality. Anyway, you solved it, so good for you. :)

**Comment by rhazor** [comment]
Your releases don't come with any .css https://github.com/abouolia/sticky-sidebar/releases

**Comment by masiorama** [comment]
My releases? I'm not involved in the development of the plugin, I was just trying to help.
Besides that, I think you are missing the point that this plugin is not supposed to create the layout itself, but only change it slightly to attach the sticky functionality. So all the css part is obviously your job to do. :) cheers!

**Comment by rhazor** [comment]
It would be obvious if it mentioned CSS at least once on the documentation.
