### ISSUE TITLE
Bug with removeResizeListener

### ISSUE THREAD

**Issue by degibons** [abouolia/sticky-sidebar#4]
The function doesn't work properly. `$element.prop('resizeListeners')` property is not removed.
```javascript
 var index = resizeListeners.indexOf(callback);
```
is always -1. 
Maybe it connected with not correct work of addResizerListener.

**Comment by abouolia** [comment]
I've fixed that, the problem was i didn't know calling a function with bind changing its ID in each calling like define new one so you can not reach to the first, so i solved this issue with that little code. https://github.com/abouolia/sticky-sidebar/blob/master/src/sticky-sidebar.js#L129

**Comment by degibons** [comment]
Do you know how to fix this bug in the first version of the plugin (v.1.0.0)? Unfortunately, I can't move to v.2, because it behave wirdly with my page layout.
