### ISSUE TITLE
How to apply only for desktop version (no mobile)

### ISSUE THREAD

**Issue by masiorama** [abouolia/sticky-sidebar#40]
Hey there, thanks for your plugin.
I am using it successfully with the desktop version of my project, but now I'm having problems with the mobile version (implemented with bootstrap) since it shouldn't work due to the different nature of the scroll usage.

Any suggestion how to selectively show the sticky sidebar depending on screen resolution?
Thanks in advance.

**Comment by Opanga** [comment]
You can use stickySidebar.destroy(); below a specific screen size to disable the scroll. 
Example:
if( $(window).innerWidth() < 750) {
	stickySidebar.destroy();
}

**Comment by masiorama** [comment]
I used the opposite logic: create only if bigger than.
Thanks, solved!

**Comment by abouolia** [comment]
@Opanga @masiorama https://abouolia.github.io/sticky-sidebar/#minwidth

**Comment by masiorama** [comment]
I completely missed that option! Thanks @abouolia !

**Comment by weilinzung** [comment]
@abouolia  I don't think the `minwidth` is working~
