### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by AlexanderPotapov** [abouolia/sticky-sidebar#42]
Hi Ahmed,

Maybe I do something wrong, but it seems like on mobile, sticky layer is always on the content. Is there any way to stop them for small displays?

Thank you.
Alexander

**Comment by abouolia** [comment]
If you mean you want to stop sticky sidebar on small screens, there's option to do that, check it out.  https://abouolia.github.io/sticky-sidebar/#minwidth

**Comment by ghost** [comment]
My conf is like
```js
      var sidebar = new StickySidebar('#sidebar', {
        topSpacing: 60,
        bottomSpacing: 60,
        containerSelector: '.main-content',
        innerWrapperSelector: '.sidebar__inner',
        // disable for small screens
        minWidth: 768
      });
```


with:

```js
  <div class="main-content">
    <div id="sidebar" class="sidebar">
      <div class="sidebar__inner">
        <%- include('../partials/shared/sidebar'); %>
      </div>
    </div>
    <div id="content" class="content">
```

and it is not working 😢
