### ISSUE TITLE
Can't navigate via tab key to entire page

### ISSUE THREAD

**Issue by joshbader** [abouolia/sticky-sidebar#43]
Hello,

While testing a site I am building that includes sticky-sidebar, I noticed that I have issues tabbing through the page. It seems that once the focus enters the object tag created by the plugin, it gets stuck.

Adding a tabindex of -1 to the object tag seems to fix it. Just one question, do you foresee any issues by adding this attribute to the object tag?

Thanks,
Josh

**Comment by abouolia** [comment]
Object tag?? You're using old version of the plugin, just use the latest version. 👍

**Comment by joshbader** [comment]
Ok, thanks.
