### ISSUE TITLE
Flickering when scrolling to bottom of page.

### ISSUE THREAD

**Issue by rbergeron81** [abouolia/sticky-sidebar#44]
This issue only happens once in a while, but does seem to occur in all browsers. When scrolling to the bottom of the page, the fixed sidebar will sometimes flicker rapidly. 

[Here is a screencap of the issue.](https://www.screencast.com/t/ua8zWLLb) The sidebar actually flickers a lot faster than in that video, but I guess video couldn't capture it the speed.

I am using this plugin in conjunction with ResizeSensor. 

It seems to be easier to recreate while dev tools/inspector is open. The issue is occurring on [this site. ](https://retroshirtzonline.flywheelsites.com/shop/)

Any help on this would be much appreciated, thanks

**Comment by planetcappe** [comment]
This is also happening to me, I'm using it on a Wordpress installation with very few plugins, it happens in every browser when the page doesn't have too much content and is a short one.

**Comment by mwhansen** [comment]
I'm also getting this when the content of the sidebar changes height:
![sticky-sidebar-jitters2](https://user-images.githubusercontent.com/374299/33488366-fab12ddc-d675-11e7-89cf-42af1980fad7.gif)

Manually scrolling will stop the jitters.

**Comment by abouolia** [comment]
I'm sure there's margin bottom in the last item that inside `.sidebar__inner`, try to remove margin bottom or  add clearfix on `.sidebar__inner`.

**Comment by rbergeron81** [comment]
Removing the margin bottom and adding the clearfix seems to have fixed it for me. Thanks!

**Comment by mwhansen** [comment]
Adding the clearfix fixed things for me.

**Comment by planetcappe** [comment]
Thank you @abouolia , for me it was margin-top the culprit.

**Comment by abouolia** [comment]
This issue must be in FAQ.
