### ISSUE TITLE
Unexpected token export ln:696

### ISSUE THREAD

**Issue by pingram3541** [abouolia/sticky-sidebar#47]
Is it possible to support the ES6 features of this plugin using vanilla js?  i.e. no package managers/compiler/polyfill?

**Comment by abouolia** [comment]
What are ES6 features that you wish be in the next versions?

**Comment by pingram3541** [comment]
Sorry if it wasn't clear.  I was simply trying to use this on a modern shared hosting platform by simply including the library and initializing but my browser doesn't support it and give the error in the title of this issue.

The export feature is the issue specifically. Tried using latest Chrome and FF.

**Comment by SoulOfNoob** [comment]
i have this issue as well :/

**Comment by BenTomsett** [comment]
I'm also trying to do the same thing, just including the library but I get an Unexpected token export. Is this not possible?

**Comment by abouolia** [comment]
I'm pretty sure wrong with including it in HTML document, try this code and it will work.

```
	<script type="module">
		import StickySidebar from './sticky-sidebar/src/sticky-sidebar.js';

		var a = new StickySidebar('#sidebar', {
			topSpacing: 20,
			bottomSpacing: 20,
			containerSelector: '.container',
			innerWrapperSelector: '.sidebar__inner'
		});
	</script> 
```

Jake Archibald wrote great article about ES6 modules in browser, check it out.   https://jakearchibald.com/2017/es-modules-in-browsers/
