### ISSUE TITLE
account for padding-top on body with fixed header

### ISSUE THREAD

**Issue by iamtekeste** [abouolia/sticky-sidebar#48]
@abouolia In this [issue](https://github.com/abouolia/sticky-sidebar/issues/36) you asked @kiwimind if there is a `padding` or `margin` on the `body` or `html` mine has `padding-top: 58px` on the `body` and the footer is not pushing the sticky sidebar at the right moment(the sticky sidebar is overlapping with the footer). How do you account for this kind of cases.

<img width="679" alt="screen shot 2017-12-05 at 3 52 15 pm" src="https://user-images.githubusercontent.com/1515815/33630256-ad0e0d9a-d9d4-11e7-9c04-7f1ef47110cc.png">

Thank you in advance!

**Comment by abouolia** [comment]
Sticky sidebar faced this issue previously but i fixed this issue in latest versions, what the version are you using? if it is not the latest version, update to latest one.

Regards.

**Comment by iamtekeste** [comment]
@abouolia I am using the latest version from NPM. 
` "sticky-sidebar": "3.3.1"`

**Comment by abouolia** [comment]
Give me sticky sidebar config.

**Comment by iamtekeste** [comment]
``` js
new StickySidebar('.product-grid__col--minor.rs-cat-nav__wrapper', {
	containerSelector: '#primary-content',
	innerWrapperSelector: '.rs-cat-nav.rs-cat-nav--anf',
	topSpacing: 100,
	bottomSpacing: 50
});
```

I will try and recreate a simplified demo on CodePen & report back here. Basically my html structure is the same as your examples, the only difference is my page has header that gets sticked/fixed on scroll.
 
 If it helps I am using the standalone version (not using the jQuery version)

Thank you so much for the plugin btw!

**Comment by iamtekeste** [comment]
@abouolia  Okay! After several hours of scratching my head I have found the root cause of the problem. It was the `padding-top` on the `#sidebar` (the actual sidebar not the inner_sidebar). I was able to reproduce this issue by adding `padding-top: 30px` to the `#sidebar` element on your basic example html. https://abouolia.github.io/sticky-sidebar/examples/basic.html
just add the padding top the sidebar element to reproduce the issue.

**Comment by geebru** [comment]
I see this was closed but I don't think it's resolved - @iamtekeste just provided replication steps but I'm still seeing this issue in the latest version.

Moving the padding to a parent, child, or the sticky element itself all cause the sidebar to dip below its lowest bound by the amount of the top padding.

Adding the `padding-top` to the example shows the bug(?) in action.

**Comment by abouolia** [comment]
Adding padding top/bottom to `.sidebar` is not possible at all, you can add it to `.sidebar__inner` and it will works.

**Comment by presto2116** [comment]
Adding padding to .sidebar__inner helped me with my issue as well. very useful. Thanks!
