### ISSUE TITLE
Sidebar to big for viewport

### ISSUE THREAD

**Issue by mick-feller** [abouolia/sticky-sidebar#50]
Hi,

First of all your plugin is amazing! works really smooth and happy i found it!

One question though, when my sidebar is bigger then the viewport is there any way for me not to scroll the sidebar up but keep it fixed top the top of the screen and "cut" off the bottom lets say.

Thanks

**Comment by mobilutz** [comment]
This is actually the one thing I miss as well.

**Comment by abouolia** [comment]
That is not possible right now, but if there is great pull request, i will merge it. Thanks.
