### ISSUE TITLE
Using sticky-sidebar and webpack

### ISSUE THREAD

**Issue by geenkaas** [abouolia/sticky-sidebar#51]
I am trying to use sticky-sidebar in my webpack setup but I run into the following error:

sticky-sidebar.js:8 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_jquery___default(...)(...).stickySidebar is not a function

I have the following js file:

import $ from 'jquery';

require('sticky-sidebar');

export default function() {
    $('.s-sidebar').stickySidebar({
        topSpacing: 60,
        bottomSpacing: 60,
        containerSelector: '.s-main',
        innerWrapperSelector: '[data-sticky]',
    });
}

Could it be that I am using the wrong version when calling require()? I installed the NPM package but I see three versions and I cannot select which one to use. I already have my own version of jQuery running (see first line) so I need a "clean" plugin.

Let me know if you are aware of this issue and if you have a solution or need more details on my setup.

EDIT: code is not formatting properly, removed.

**Comment by abouolia** [comment]
I tested it with Webpack and it works without any error, i'm pretty sure the wrong with your config code. 

This is code of my test with Webpack.
`` 
import StickySidebar from './node_modules/sticky-sidebar'
;
var sidebar = new StickySidebar('#sidebar', {
    bottomSpacing: 20,
    topSpacing: 20,
    containerSelector: '.container',
    innerWrapperSelector: '.sidebar__inner'
});
```

**Comment by yudonghan** [comment]
I found the same issue, the reason is my project use server render React component, so 'window' undefined will stop the server, resolve is to require in componentDidMount()

**Comment by jaykhatri2020** [comment]
@abouolia Thanks for a simple solution but difficult to find on Google :)

I am using  sticky-sidebar-v3 and the same solution work in Angular 16.

**Comment by DarkcoderSe** [comment]
@yudonghan do you have any example to use in react? I'm facing issues, I'm also using NextJS's SSR.

**Comment by jaykhatri2020** [comment]
@DarkcoderSe  can you please create an example in stackblitz so we can debug,
