### ISSUE TITLE
Update options after init

### ISSUE THREAD

**Issue by reardestani** [abouolia/sticky-sidebar#52]
Is it possible to update options after init?

For example, the top spacing is set to 50 by default but I need to increase it to 100 when a custom event triggered in my page.

**Comment by konutis** [comment]
The same here.

**Comment by abouolia** [comment]
Seems you didn't read the documentation well, no problem, here's how to do that.

``` 
new StickySidebar({
    topSpacing: function(){
       var x = 60;
        return x;
    },
    bottomSpacing: function(){
       var x = 60;
        return x;
    },
});
```

The function of `topSpacing` and `bottomSpacing` will be called on every scroll or resize change.
