### ISSUE TITLE
Sidebar fits viewport method need to take top/Bottom spacing into the equation

### ISSUE THREAD

**Issue by renatodeleao** [abouolia/sticky-sidebar#53]
Heys, first thanks for the awesome work on this!

### Context
I detected a small bug on the calculation. In lookalike "scrollable example" my sidebar was bigger that viewport by just a few pixels and got cropped ( didn't scroll through and affix bottom)

So a viewport with 500px height, a sidebar with `499px` height with a `topSpacing` of, for example `100px`, doesn't produce the "scrollable effect", because `isSidebarFitsViewport()` returns `true`

### Current and Expected behaviour

(expected after code editing)

![gif](https://d2ffutrenqvap3.cloudfront.net/items/1o0d261j2h2I0c3f132V/Screen%20Recording%202017-12-26%20at%2006.51%20PM.gif?v=fb193ea3)

A [Pen](https://codepen.io/ohsimtabem/pen/GyrmaK) is available for testing. For this demo, just resize the window to something between `500px < x < 572px` ( sidebar height + TopSpacing)

### Fix
I didn't go through the entire codebase but, i assume that top and bottom spacing should be added to the equation depending on the `this.scrollDirection`. 

```javascript    
/**
  * Determine whether the sidebar is bigger than viewport.
  * @public
  * @return {Boolean}
 */
isSidebarFitsViewport(){
let offset = this.scrollDirection === 'down' ? this.dimensions.lastBottomSpacing : this.dimensions.lastTopSpacing;

 return this.dimensions.sidebarHeight + offset < this.dimensions.viewportHeight;
}
```

Thanks once again!

**Comment by lipsum83** [comment]
Same problem here, I have a sidebar that dynamically loads content, and some times that content is just a little bit bigger than the viewport (by a factor of options.topSpacing or less) and, in those cases, the sidebar gets cropped. After some looking at the code I came to the same conclusion than @renatodeleao, that the code needs to take into consideration the top and bottom spacing (defined on the initialization options) when calculating if the sidebar actually fits the viewport. By no means did I go through all the code base, so I might been overlooking something, but in my tests, the change proposed by @renatodeleao, seems to do the trick.

**Comment by abouolia** [comment]
Can you give a pen on codepen.io that has this issue? i tried same scenario on my examples and i didn't see this issue at all.

**Comment by renatodeleao** [comment]
@abouolia => https://codepen.io/ohsimtabem/pen/GyrmaK

Here's a video explaining before and after fix: https://cl.ly/2R1S1h3k3X1p

**Comment by abouolia** [comment]
Great contribution @renatodeleao, It fixed as you suggested, Thanks a lot.

**Comment by renatodeleao** [comment]
@abouolia no prob, thank you for this awesome piece of code!
