### ISSUE TITLE
Issue with Bootstrap column

### ISSUE THREAD

**Issue by minimaluminium** [abouolia/sticky-sidebar#55]
The sidebar width increases while scrolling. Here is the demo. https://codepen.io/sodbileg/pen/QazKEe

**Comment by davidkrijgsman** [comment]
You can fix this by adding an additional element for your content (see div.actual-content in https://codepen.io/anon/pen/qxEjya) and adding some padding css with a superhacky selector (`.sidebar-inner[style^="position: fixed"]`, which is just terrible).

The affixed class is applied whenever you scroll past its original y-position, which makes sense, but that way you can't detect whether it's stuck to the container bottom and the css position is set to relative. 

Ideally I'd like an extra class like .is-affixed-bottom or something, applied when the sticky element is stuck to the bottom of the container. That way you can undo the extra padding when the element's css position is set to relative.

**Comment by abouolia** [comment]
https://codepen.io/abouolia/pen/PRqVRK
