### ISSUE TITLE
Replace resize sensor with resize observer?

### ISSUE THREAD

**Issue by souporserious** [abouolia/sticky-sidebar#56]
First, thank you for such a wonderful plugin! I was curious if you would be willing to replace the resize sensor with a native [resize observer](https://developers.google.com/web/updates/2016/10/resizeobserver)? There is a nice [polyfill here](https://github.com/que-etc/resize-observer-polyfill). I can an add a PR, please let me know.

**Comment by abouolia** [comment]
Resize observer is still new specification and we didn't see many browser support it yet except in Chrome 64 we have no problem in that at all if there's a great polyfill, but resize observer polyfill that you mentioned relies on Mutation Observer with a fallback to Mutation Events for IE 9 and IE 10, at first glance that is so convenient but when we look deeply, Mutation Events is slow and has some performance issues that would be disaster if it implemented on this tool. i appreciate your contribution thanks.

Regards.
