### ISSUE TITLE
UglifyJS: Unexpected token: punc ()) - Webpack

### ISSUE THREAD

**Issue by jonasspott** [abouolia/sticky-sidebar#59]
Hi

I get this error when trying to minify sticky-sidebar through UglifyJS within Webpack 3.10.
`Unexpected token: punc ())`

**I use this version of babel:**
`"babel-preset-env": "^1.6.1"`

**The error only occurs when importing sticky-sidebar:**
`import "sticky-sidebar";`

**UglifyJS settings**:
`
            new UglifyJSPlugin({
                beautify: false,
                mangle: {
                    screw_ie8: true,
                    keep_fnames: true
                },
                compress: {
                    screw_ie8: true
                },
                comments: false
            }),
`

**Error:**
`
ERROR in stickySidebar-302051997b86aa81111e.js from UglifyJs
Unexpected token: punc ()) [stickySidebar-302051997b86aa81111e.js:154,24]
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--2-2!../node_modules/postcss-loader/lib/index.js??ref--2-3!../node_modules/resolve-url-loader/index.js!../node_modules/sass-loader/lib/loader.js??ref--2-5!sass/style.sass:
     2 assets
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [build-production] Error 1
`

Is this a known problem - or do I do something wrong here? :)

Jonas

**Comment by gerarrd** [comment]
How did you solve this one?

**Comment by geenkaas** [comment]
I am running into the exact same problem with uglifyjs and sticky-sidebar and would like to know if the  @abouolia or @jonasspott  has a solution we can all use.

**Comment by palicko** [comment]
I solved it importing it like this:
`import StickySidebar from 'sticky-sidebar/dist/sticky-sidebar';`
