### ISSUE TITLE
destroy sticky bar in mobile view

### ISSUE THREAD

**Issue by aruna-live** [abouolia/sticky-sidebar#63]
I need to disable sticky bar in mobile view. (<=768px). how can I disable sticky bar? also it should work when resize the window. ex: on ipad in landscape mode should work side sticky bar and when rotate it to portrait mode sticky bar should be disable.

Thank you very much.

**Comment by fonpixel** [comment]
@aruna-live https://abouolia.github.io/sticky-sidebar/#usage-with-resizesensorjs
With this additional plugin sticky-sidebar works great for me.

**Comment by peterrogov** [comment]
Have the same issue. Inclusion of ResizeSensor does not help. Can't disable sticky sidebar in mobile view.

**Comment by humbertqz** [comment]
I've tried this and it's working for me:

`
if ( window.innerWidth < 768 ) {
        sidebar.destroy();
    } else if( window.innerWidth > 768 ){
        sidebar.updateSticky();
    }
`

**Comment by abouolia** [comment]
https://abouolia.github.io/sticky-sidebar/#minwidth

**Comment by fiazmr2** [comment]
> https://abouolia.github.io/sticky-sidebar/#minwidth

for disabling mobile and including iPads, value should be 
minWidth: 767
and not 
minWidth: 768. When set at 768 iPad portrait resolution is not sticky
