### ISSUE TITLE
Unstick in responsive mode

### ISSUE THREAD

**Issue by masoudmanson** [abouolia/sticky-sidebar#64]
How can I unstick sidebar in responsive mode. I tried destroy() method but it doesn't work.

**Comment by lorenzwoehr** [comment]
I'm having the same issue. How did you get stickySidebar.destroy(); to work?

**Comment by masoudmanson** [comment]
You don't need to call destroy() method at all. All you have to do is to provide a `minWidth` attribute so the stickySidebar will know when to become disabled. For example, if you want your sidebar to be static in devices narrower than 920px, you can simply do as follow:
`var sidebar = new StickySidebar('#sidebar', {
    minWidth: 920
  });`
