### ISSUE TITLE
destroy and re-activate cause error!

### ISSUE THREAD

**Issue by ve3** [abouolia/sticky-sidebar#7]
I have add this code because when the window resized, the header navbar height changed.

```js
$(window).on('resize', function() {
    console.log('window resize');
    $('.rd-sidebar').stickySidebar('destroy');
    $('.rd-sidebar').stickySidebar({
        containerSelector: '.rd-page-wrapper',
        innerWrapperSelector: '.rd-sidebar-inner',
        minWidth: 1000,
        resizeSensor: true,
        topSpacing: $('.rd-navbar').height(),
    });
});
```

When the window was resized the sticky menu destroyed successfully but when it re-activate, in the console window show me this.

> TypeError: g.contentDocument is null sticky-sidebar.min.js:1:6965

**Comment by abouolia** [comment]
First of all you're using the plugin absolutely wrong. Resize event is handled inside the plugin so you don't have to put initialize function inside resize handler (this is disaster), anyway here's the right way to initialize the plugin with your options and i recommend you to read the documentation well.
```
$('.rd-sidebar').stickySidebar({
        containerSelector: '.rd-page-wrapper',
        innerWrapperSelector: '.rd-sidebar-inner',
        minWidth: 1000,
        resizeSensor: true,
        topSpacing: $('.rd-navbar').height(),
    });
```
Secondly you're destroying the plugin on the element before even initialize it of normal it will show this type of error.

**Comment by ve3** [comment]
I have to use window.on resize because the plugin cannot update top spacing.

`$('.rd-sidebar').stickySidebar('destroy');` show that error!

**Comment by abouolia** [comment]
When i developed this plugin i put this issue into account.

```
$('.rd-sidebar').stickySidebar({
        containerSelector: '.rd-page-wrapper',
        innerWrapperSelector: '.rd-sidebar-inner',
        minWidth: 1000,
        resizeSensor: true,
        topSpacing: function(){
              return $('.rd-navbar').height();
       }
    });
```
Regards
