### ISSUE TITLE
Not work in ie11 (Syntax error)

### ISSUE THREAD

**Issue by mikhaylenko** [abouolia/sticky-sidebar#93]
![2018-10-29_130921](https://user-images.githubusercontent.com/7305147/47646296-2b14a100-db7c-11e8-8099-33809150bd64.jpg)

How I use

`  
import StickySidebar from 'sticky-sidebar';

let a = new StickySidebar('.Sidebar__wrapper', {
    topSpacing: 80,
    resizeSensor: true,
    minWidth: 980,
  });` 

I include polyfills into my projects? such us:
`require('es6-promise').polyfill();
import 'core-js/fn/array/from';
import 'core-js/es6/symbol';
import 'core-js/fn/symbol/iterator';`

Maybe I need any more polyfills?

**Comment by sermo-de-arboribus** [comment]
This is not a polyfill issue. Rather the included module file does not get transpiled, and therefore contains arrow function syntax, which IE doesn't understand. 
If you are using webpack and babel you can force a module transpilation with the following setting in the module rules section of your webpack.config.js:
```javascript
test: /\.js$/,
exclude: /node_modules(?!\/sticky-sidebar)/,
use: "babel-loader"
```

**Comment by stijnelskens** [comment]
aaaaallllllleeeeeeeeeeeeeeeeee, ik word hier wild!

**Comment by stijnelskens** [comment]
Fix by Yarn remove and adding it to my src folder ¯\_(ツ)_/¯

**Comment by x1oJ0** [comment]
Or you can simply use dist version of stickysidebar such as: 
`import StickySidebar from 'sticky-sidebar/dist/sticky-sidebar';`

Then it works in IE11 as well.
